package org.afeka.fi.backend.pojo.report;

public enum FiErrorName {
    MISSING_STEP,MISSING_NEXT_YES_STEP,MISSING_NEXT_NO_STEP,MISSING_LINK,MISSING_DESCRIPTION,FI_UNVALID,OCR_GENERAL_ERROR,FORMAT_NOT_SUPPORT
}
